'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const S=require('../src/finance/simulation-backtest-core.js');
const near=(a,b,t=1e-9)=>assert.ok(a!=null&&Math.abs(a-b)<=t,`${a} not within ${t} of ${b}`);
const days=(n,start=Date.UTC(2026,0,1),step=86400000,fn=i=>100)=>Array.from({length:n},(_,i)=>({date:start+i*step,close:fn(i)}));

test('SB-REG-001 Monte Carlo preserves explicit zero return and volatility',()=>{const r=S.monteCarloRun({initial:100,expectedReturn:0,volatility:0,horizonYears:1,simulations:20,seed:7,target:100,stepsPerYear:12});assert.equal(r.median,100);assert.equal(r.min,100);assert.equal(r.max,100);assert.equal(r.pTarget,1);});
test('SB-REG-002 Monte Carlo rejects zero initial capital instead of defaulting to 100',()=>assert.equal(S.monteCarloRun({initial:0,expectedReturn:0,volatility:0,horizonYears:1,simulations:10,seed:1,target:100,stepsPerYear:12}),null));
test('SB-REG-003 Monte Carlo is reproducible for the same seed',()=>{const a=S.monteCarloRun({initial:100,expectedReturn:.08,volatility:.2,horizonYears:1,simulations:200,seed:42,target:110,stepsPerYear:12});const b=S.monteCarloRun({initial:100,expectedReturn:.08,volatility:.2,horizonYears:1,simulations:200,seed:42,target:110,stepsPerYear:12});assert.deepEqual(a,b);});
test('SB-REG-004 Monte Carlo validates simulation and step counts',()=>{assert.equal(S.monteCarloRun({simulations:0}),null);assert.equal(S.monteCarloRun({simulations:1.5}),null);assert.equal(S.monteCarloRun({stepsPerYear:0}),null);});
test('SB-REG-005 zero-volatility target probability is exact',()=>{const hi=S.monteCarloRun({initial:100,expectedReturn:0,volatility:0,horizonYears:1,simulations:10,seed:2,target:101,stepsPerYear:12});const lo=S.monteCarloRun({initial:100,expectedReturn:0,volatility:0,horizonYears:1,simulations:10,seed:2,target:99,stepsPerYear:12});assert.equal(hi.pTarget,0);assert.equal(lo.pTarget,1);});

test('SB-REG-006 backtest rejects zero initial capital',()=>{const r=S.backtestRun({prices:days(30),initialCapital:0,signal:Array(30).fill(0)});assert.equal(r.available,false);assert.match(r.reason,/initial capital/i);});
test('SB-REG-007 backtest rejects zero rebalance interval',()=>{const r=S.backtestRun({prices:days(30),rebalanceEvery:0,signal:Array(30).fill(0)});assert.equal(r.available,false);assert.match(r.reason,/rebalance/i);});
test('SB-REG-008 current-close signal cannot earn the already-finished current return',()=>{const p=days(30,Date.UTC(2026,0,1),86400000,i=>i===0?100:110);const signal=Array(30).fill(1);signal[0]=0;const r=S.backtestRun({prices:p,signal,initialCapital:100000,transactionCost:0,slippage:0,rebalanceEvery:1});assert.equal(r.available,true);assert.equal(r.equityCurve[1],100000);});
test('SB-REG-009 transaction costs are deducted at turnover and flips charge two-sided turnover',()=>{const p=days(30);const signal=Array(30).fill(-1);signal[0]=1;const r=S.backtestRun({prices:p,signal,initialCapital:100000,transactionCost:.01,slippage:0,rebalanceEvery:1});assert.equal(r.available,true);near(r.equityCurve[0],99000);near(r.equityCurve[1],97020);near(r.costs,2980);near(r.totalTurnover,3);});
test('SB-REG-010 filtered backtests keep signal alignment to original price indices',()=>{const p=days(40,Date.UTC(2026,0,1),86400000,i=>100+i);const signal=Array(40).fill(1);for(let i=10;i<40;i++)signal[i]=-1;const r=S.backtestRun({prices:p,signal,startDate:p[10].date,initialCapital:100000,transactionCost:0,slippage:0,rebalanceEvery:1});assert.equal(r.available,true);assert.equal(r.positionCurve[0],-1);assert.ok(r.equityCurve[1]<r.equityCurve[0]);});
test('SB-REG-011 weekly timestamps infer weekly rather than hard-coded 252 annualization',()=>{const p=days(30,Date.UTC(2026,0,1),7*86400000,i=>100+i);const r=S.backtestRun({prices:p,signal:Array(30).fill(0),transactionCost:0,slippage:0});assert.equal(r.available,true);assert.equal(r.annualizationFactor,52);assert.equal(r.periodLabel,'weekly');});
test('SB-REG-012 benchmark active return compares annualized strategy and benchmark on the same basis',()=>{const p=days(30,Date.UTC(2026,0,1),86400000,i=>100*Math.pow(1.001,i));const b=days(30,Date.UTC(2026,0,1),86400000,i=>100*Math.pow(1.0005,i));const r=S.backtestRun({prices:p,benchmarkPrices:b,signal:Array(30).fill(1),transactionCost:0,slippage:0});assert.equal(r.available,true);near(r.activeRet,r.cagr-r.benchmarkCagr,1e-12);assert.equal(r.alignedPeriods,29);});
