'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const L=require('../src/finance/workstation-ledger-core.js');
const near=(a,b,t=1e-9)=>assert.ok(a!=null&&Math.abs(a-b)<=t,`${a} not within ${t} of ${b}`);

test('WL-REG-001 dividend supports production grossDividend fields and zero withholding',()=>assert.deepEqual(L.dividendAmounts({grossDividend:100,withholdingTax:0}),{gross:100,withholding:0,net:100}));
test('WL-REG-002 dividend supports shares times dividend per share',()=>assert.deepEqual(L.dividendAmounts({sharesHeld:20,dividendPerShare:2,withholdingTax:5}),{gross:40,withholding:5,net:35}));
test('WL-REG-003 BUY ledger records cost basis, fees and tax cash outflow',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'BUY',security:'ABC',quantity:10,price:20,fees:2,tax:1,currency:'EUR'}],'EUR');assert.equal(r.positions.ABC.quantity,10);assert.equal(r.positions.ABC.costBasis,200);assert.equal(r.positions.ABC.fees,2);assert.equal(r.cash.EUR,-203);});
test('WL-REG-004 SELL ledger realizes PnL against proportional cost basis',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'BUY',security:'ABC',quantity:10,price:20,currency:'EUR'},{date:'2026-02-01',type:'SELL',security:'ABC',quantity:4,price:30,fees:2,tax:1,currency:'EUR'}],'EUR');assert.equal(r.positions.ABC.quantity,6);assert.equal(r.positions.ABC.costBasis,120);assert.equal(r.positions.ABC.realizedPnl,37);assert.equal(r.cash.EUR,-83);});
test('WL-REG-005 oversell is capped and explicitly warned',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'BUY',security:'ABC',quantity:2,price:10},{date:'2026-02-01',type:'SELL',security:'ABC',quantity:5,price:15}]);assert.equal(r.positions.ABC.quantity,0);assert.ok(r.warnings.some(x=>x.code==='LEDGER-OVERSELL-CAPPED'));});
test('WL-REG-006 negative withdrawal reduces rather than increases cash',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'DEPOSIT',amount:100},{date:'2026-02-01',type:'WITHDRAWAL',amount:-25}]);assert.equal(r.cash.EUR,75);});
test('WL-REG-007 dividend ledger posts gross income and net cash',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'DIVIDEND',security:'ABC',grossDividend:100,withholdingTax:15}]);assert.equal(r.positions.ABC.divIncome,100);assert.equal(r.positions.ABC.divNet,85);assert.equal(r.cash.EUR,85);});
test('WL-REG-008 explicit zero split ratio is invalid instead of silently becoming 2-for-1',()=>{const r=L.calculateLedger([{date:'2026-01-01',type:'BUY',security:'ABC',quantity:2,price:10},{date:'2026-02-01',type:'SPLIT',security:'ABC',splitRatio:0}]);assert.equal(r.positions.ABC.quantity,2);assert.ok(r.warnings.some(x=>x.code==='LEDGER-SPLIT-INVALID'));});
test('WL-REG-009 position base value and unrealized PnL preserve zero cost basis',()=>{assert.equal(L.positionBaseValue({quantity:2},50,1.1),110);const x=L.positionUnrealized({quantity:2,costBasis:0},50);assert.equal(x.marketValue,100);assert.equal(x.unrealizedPnl,100);assert.equal(x.returnOnCost,null);});
test('WL-REG-010 market-value summary separates local and FX effects',()=>{const r=L.marketValueSummary([{position:{quantity:2,costBasis:80,fxBasis:1},price:50,fxRate:1.2}]);assert.equal(r.mv,120);assert.equal(r.cost,80);assert.equal(r.unreal,40);assert.equal(r.localUnrealized,20);near(r.fxUnrealized,16);});
test('WL-REG-011 cash summary preserves zero balances and reports missing FX',()=>{const r=L.cashSummary({EUR:{balance:0},USD:{balance:100},GBP:{balance:50}},{USD:0.9},'EUR',200);assert.equal(r.localCash.EUR,0);assert.equal(r.cash,90);assert.deepEqual(r.missingFxCurrencies,['GBP']);assert.equal(r.total,290);});
test('WL-REG-012 ledger sorting is deterministic by date/timestamp/id',()=>{const r=L.sortTransactions([{id:'b',date:'2026-02-01'},{id:'a',date:'2026-01-01'}]);assert.equal(r[0].id,'a');});
